tasks:
  - name: Install
    before: |
      make create-workspace
    init: |
      make start-workspace

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
    - sourcegraph.cody-ai
    - eamodio.gitlens
    - NicolasVuillamy.vscode-groovy-lint
    - medo64.render-crlf
    - esbenp.prettier-vscode
    - tamasfe.even-better-toml
    - ms-python.python
    - charliermarsh.ruff
    - bierner.markdown-mermaid
    - hashicorp.terraform

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true

ports:
  - port: 4566
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: open-preview
    visibility: public

env:
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
  AWS_REGION: ${AWS_REGION:-us-east-1}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
  AWS_ENDPOINT_URL: http://localhost:4566
  ENDPOINT_URL: http://localhost:4566
