version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: terraform-alb-failover-localstack
    ports:
      - "4566:4566"            # LocalStack Edge Proxy
      - "4571:4571"            # LocalStack Edge Proxy (external)
    environment:
      - SERVICES=s3,ec2,elbv2,route53,apigateway,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test_key}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test_secret}
      - EDGE_PORT=4566
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # Optional: for pro features
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge
